defaults:
  - config: default
  - optimization_config: default
  - data_config: default
  - pretraining_metrics_config: default
  - final_validation_metrics_config: default
  - wandb_logger_kwargs: default
  - trainer_config: default

experiment_dir:
  value: ???
do_overwrite:
  value: False

num_dataloader_workers:
  value: ???

do_final_validation_on_metrics:
  value: True
