name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/*", "dev"]

jobs:
  run_tests_ubuntu:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file env_cpu.yml --name base
          pip install pytest
          pip install sh

      - name: List dependencies
        run: |
          conda list

      - name: Run pytest
        run: |
          pytest -v --doctest-modules --ignore docs/

  # upload code coverage report
  code-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file env_cpu.yml --name base
          pip install pytest
          pip install pytest-cov[toml]
          pip install sh

      - name: Run tests and collect coverage
        run: pytest --doctest-modules --cov EventStream --ignore docs/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
